### ISSUE TITLE
An I/O error occured: stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by JacobHenner** [saghm/rural#1]
Command: `rural get https://www.google.com`

Expected behaviour: Display content of www.google.com 
Actual behaviour: Error message -- `An I/O error occured: stream did not contain valid UTF-8`

`rural head https://www.google.com/` works as expected, though.

**Comment by saghm** [comment]
Sorry for the delayed response! Fixed in d6b0ee588010809a78b1b57161154f71da2106de, and published ion version 0.7.1.
